version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node:
    image: node
    restart: always
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
