version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

  adminer:
    image: adminer
    restart: always
    ports:
      - $ADMINER_PORT:$ADMINER_PORT

  node:
    image: node
    restart: always
    ports:
      - $NODE_PORT:$NODE_PORT
    tty: true
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
